ALTER TABLE billing_orders
  ADD COLUMN status VARCHAR(32) DEFAULT 'served' AFTER total_amount,
  ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at; 